prerender:
    extends:
        file: docker-compose-common.yml
        service: prerender
    environment:
        ALLOWED_DOMAINS: citypantry.dev
        PRERENDER_NUM_WORKERS: 1
        PRERENDER_NUM_ITERATIONS: 20
        VIRTUAL_HOST: prerender.citypantry.dev
    env_file: .env
    links:
        - "redis:redis"
    restart: always
redis:
    extends:
        file: docker-compose-common.yml
        service: redis
    restart: always
