version: '2'
services:
  prerender:
    restart: always
    extends:
      file: docker-compose.common.yml
      service: prerender
    environment:
      ALLOWED_DOMAINS: citypantry.com
      PRERENDER_NUM_WORKERS: 2
      PRERENDER_NUM_ITERATIONS: 20
      VIRTUAL_HOST: prerender.tech.citypantry.com,prerender.citypantry.com
    links:
      - 'redis:redis'
    networks:
      - frontend_network
      - backend_network

  redis:
    extends:
      file: docker-compose.common.yml
      service: redis
    networks:
      - backend_network

networks:
  frontend_network:
    external: true
  backend_network:

