version: '2'
services:
  prerender:
    build: .
    environment:
      CACHE_MAXSIZE: 100
      CACHE_TTL: 60
      REDIS_CACHE_TTL: 3600
      REDIS_HOST: redis
      REDIS_PORT: 6379
      HTTPS_METHOD: noredirect
      PORT: 3000
      PRERENDER_NUM_WORKERS: 2
      PRERENDER_NUM_ITERATIONS: 30
    env_file: .env

  redis:
      image: redis:3

