---
# tasks file for delpoy



- name: Create Folder with certificates 
  become: yes
  become_user: root
  file:
    path: /etc/docker_env
    state: directory


- name: Create env from template
  become: yes
  become_user: root
  template: 
    src: prerender.env.j2
    dest: /etc/docker_env/prerender.env


- name: Stop prerender
  become: yes
  become_user: root
  shell:
    chdir: /etc/docker_env/
    cmd: docker stop prerender


- name: Start prerender
  become: yes
  become_user: root
  shell:
    chdir: /etc/docker_env/
    cmd: docker run --rm --name prerender --hostname prerender.services.lokalebasen.dk -m 1024m -v /var/log/docker/prerender:/var/log -v /etc/hosts:/etc/hosts:ro -p 0.0.0.0:50032:8080 --env-file /etc/docker_env/prerender.denv -d matchoffice/prerender:latest
  





      
  