---
# tasks file for delpoy



- name: Create Folder with certificates 
  become: yes
  become_user: root
  file:
    path: /etc/docker_env/prerender
    state: directory


- name: Create env from template
  become: yes
  become_user: root
  template: 
    src: prerender.env.j2
    dest: /etc/docker_env/prerender/prerender.env

- name: Create docker-compose.yml from template
  become: yes
  become_user: root
  template: 
    src: docker-compose.yml.j2
    dest: /etc/docker_env/prerender/docker-compose.yml


- name: Start prerender
  become: yes
  become_user: root
  shell:
    chdir: /etc/docker_env/prerender
    cmd: docker-compose up --force-recreate -d
  